language: node_js
node_js:
  - 9.8.0
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - main
deploy:
  provider: pages
  local-dir: public
  skip_cleanup: true
  target-branch: master
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
before_install:
  - npm install -g yarn
  - npm install
install:
  - yarn
after_success:
  - yarn run build
  - yarn run codeclimate